### PR TITLE
Added ability to filter by versions

### PR DESCRIPTION
**Pull request by Hoppi164**
Added 'sample_name' option to allow for filtering of version names.
IE: Only cleanup versions with names that contain "prod"

### CODE REVIEW

**Comment by Hoppi164** [comment]
I'm closing this pull request.
- no response from repo owner for over 1 year.

**Comment by dgrant** [comment]
@gavin-haynes-grow are you able to help merge this?

**Comment by dgrant** [comment]
Gavin's not there either. I don't know of anyone at grow anymore who can help.

**Review by dgrant — COMMENTED** [review]
Looks good, I don't love the name `sample_name`, my suggestion would be `name_filter` or something like that... hopefully someone can merge this. It was a useful little function that we basically ran on every single deployment to appengine across several projects/services.

**Comment by Hoppi164** [comment]
Hey!

yeah i created this code modification at one of my previous jobs.
we found the app-engine clean script really useful, but needed the ability to filter based on version number to help manage things. I hadn't heard from you guys for awhile so just assumed it wasn't on the radar.

Let me know if you'd like me to re-open this pull request.
I'm happy to change the option to `name_filter`, that makes sense

**Comment by dgrant** [comment]
@jeremy-mohr @Hoppi164 can you re-open?

**Comment by Hoppi164** [comment]
Hi David
I was unable to re-open this pull request as I'd already deleted my local repo.
However I've just re-created this in a new PR including the `version_name` change you suggested

The new Pull Request is located here https://github.com/poweredbygrow/appengine_clean/pull/11

**Pull request closed without merging**
